version: "3.9"

services:
  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: root
      DB_PASSWORD: root
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  adminer:
    image: adminer
    ports:
     - "8080:8080"
    depends_on:
      - db
